namespace Client.Drivers;

public enum CB_INSTALL_FLAGS
{
	INSTALL_REMOVE_OLD_VERSIONS = 1,
	INSTALL_KEEP_START_TYPE = 2,
	INSTALL_REQUESTS_VIA_DRIVER_STACK = 4,
	INSTALL_ALWAYS_PREPARE_FILES = 0x10000,
	INSTALL_FORCE_APP_PERMISSION_CHECK = 0x20000,
	INSTALL_FORCE_SECURITY_CHECKS = 0x40000
}
